# Generated by Django 4.2.9 on 2024-01-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='apporved',
            new_name='approved',
        ),
    ]
